//**********************************************************************************
// This file is generated by a T4 template.  Any modifications to this file will
// be overridden the next time this file is generated.  DO NOT MODIFY THIS FILE!!!
//**********************************************************************************
using Ninject.StandardKernelHelper;
using Business.Domain.Interfaces;
using NUnit.Framework;
using System.Linq;

namespace DomainInventory
{
    [TestFixture]
    public partial class IDomainRepositoryNHibernateIntegrationTests
    {

    }
}
