INSERT INTO Vehicle (year, make, model) VALUES (1909, 'Ford', 'Model T')
INSERT INTO Vehicle (year, make, model) VALUES (1926, 'Chrysler', 'Imperial')
INSERT INTO Vehicle (year, make, model) VALUES (1948, 'Citroën', '2CV')
INSERT INTO Vehicle (year, make, model) VALUES (1950, 'Hillman', 'Minx Magnificent')
INSERT INTO Vehicle (year, make, model) VALUES (1953, 'Chevrolet', 'Corvette')
INSERT INTO Vehicle (year, make, model) VALUES (1954, 'Chevrolet', 'Corvette')
INSERT INTO Vehicle (year, make, model) VALUES (1954, 'Cadillac', 'Fleetwood')
INSERT INTO Vehicle (year, make, model) VALUES (1955, 'Chevrolet', 'Corvette')
INSERT INTO Vehicle (year, make, model) VALUES (1955, 'Ford', 'Thunderbird')
INSERT INTO Vehicle (year, make, model) VALUES (1956, 'Chevrolet', 'Corvette')
INSERT INTO Vehicle (year, make, model) VALUES (1957, 'Chevrolet', 'Corvette')
INSERT INTO Vehicle (year, make, model) VALUES (1957, 'BMW', '600')
INSERT INTO Vehicle (year, make, model) VALUES (1958, 'Chevrolet', 'Corvette')
INSERT INTO Vehicle (year, make, model) VALUES (1958, 'Ford', 'Thunderbird')
INSERT INTO Vehicle (year, make, model) VALUES (1959, 'Austin', 'Mini')
INSERT INTO Vehicle (year, make, model) VALUES (1959, 'Chevrolet', 'Corvette')
INSERT INTO Vehicle (year, make, model) VALUES (1959, 'BMW', '600')
INSERT INTO Vehicle (year, make, model) VALUES (1960, 'Chevrolet', 'Corvair')
INSERT INTO Vehicle (year, make, model) VALUES (1960, 'Chevrolet', 'Corvette')
INSERT INTO Vehicle (year, make, model) VALUES (1960, 'Fillmore', 'Fillmore')
INSERT INTO Vehicle (year, make, model) VALUES (1960, 'Fairthorpe', 'Rockette')
INSERT INTO Vehicle (year, make, model) VALUES (1961, 'Austin', 'Mini Cooper')
INSERT INTO Vehicle (year, make, model) VALUES (1961, 'Studebaker', 'Avanti')
INSERT INTO Vehicle (year, make, model) VALUES (1961, 'Pontiac', 'Tempest')
INSERT INTO Vehicle (year, make, model) VALUES (1961, 'Chevrolet', 'Corvette')
INSERT INTO Vehicle (year, make, model) VALUES (1962, 'Pontiac', 'Grand Prix')
INSERT INTO Vehicle (year, make, model) VALUES (1962, 'Chevrolet', 'Corvette')
INSERT INTO Vehicle (year, make, model) VALUES (1962, 'Studebaker', 'Avanti')
INSERT INTO Vehicle (year, make, model) VALUES (1962, 'Buick', 'Special')
INSERT INTO Vehicle (year, make, model) VALUES (1963, 'Austin', 'Mini')
INSERT INTO Vehicle (year, make, model) VALUES (1963, 'Austin', 'Mini Cooper S')
INSERT INTO Vehicle (year, make, model) VALUES (1963, 'Rambler', 'Classic')
INSERT INTO Vehicle (year, make, model) VALUES (1963, 'Ford', 'E-Series')
INSERT INTO Vehicle (year, make, model) VALUES (1963, 'Studebaker', 'Avanti')
INSERT INTO Vehicle (year, make, model) VALUES (1963, 'Pontiac', 'Grand Prix')
INSERT INTO Vehicle (year, make, model) VALUES (1963, 'Chevrolet', 'Corvair 500')
INSERT INTO Vehicle (year, make, model) VALUES (1963, 'Chevrolet', 'Corvette')
INSERT INTO Vehicle (year, make, model) VALUES (1964, 'Chevrolet', 'Corvette')